### PR TITLE
Broken imports endpoint.

### LINKED ISSUE #132: Endpoint to list broken imports.

### PR DESCRIPTION
**Pull request by Foxcapades**
Adds a new admin endpoint that lists datasets that failed to import due to a plugin internal error.

Example response:
```json
{
    "meta": {
        "count": 1,
        "limit": 100,
        "offset": 0
    },
    "results": [
        {
            "datasetId": "ivWnUj0JhGwAAQ",
            "owner": 221741260,
            "datasetType": {
                "name": "noop",
                "displayName": "Example Plugin",
                "version": "1.0"
            },
            "projectIds": [
                "PlasmoDB"
            ],
            "messages": [
                "Here's a validation warning about /tmp/2c66d38b-2cf9-44b8-9b48-0dff41c03726/input/Untitled.png that will be printed to STDOUT"
            ]
        }
    ]
}
```

Closes #132

### CODE REVIEW

**Comment by Foxcapades** [comment]
Hmm... needs import messages in the response body.

File: modules/rest-service/src/main/kotlin/org/veupathdb/service/vdi/util/dates.kt [hunk 1]
```diff
@@ -0,0 +1,251 @@
...
+private const val lenMonth  = 7
+private const val lenDay    = 10
+private const val lenHour   = 13
+private const val lenMinute = 16
+private const val lenSecond = 19
+private const val lenMillis = 23
+private const val lenUTC    = 24
+private const val lenZoned  = 29
+
+fun fixVariableDateString(date: String, fn: () -> Exception = ::Exception): OffsetDateTime {
```
Comment (dmgaldi) [inline modules/rest-service/src/main/kotlin/org/veupathdb/service/vdi/util/dates.kt:17]: Did we need to be able to parse variable-length dates as opposed to just requiring a full ISO Date? Seems like invalid date string that happen to match one of these lengths could result in confusing errors but that might be an unlikely scenario.

Comment (Foxcapades) [reply modules/rest-service/src/main/kotlin/org/veupathdb/service/vdi/util/dates.kt:17]: I may have been very bored at the time and severely over-engineered this to solve a problem that is unlikely to ever exist.  It's a perfectly reasonable solution to just say "give us a valid date format" rather than try to expand whatever weird thing the user gave us.
